version: "3.9"

services:
    web:
        build: .
        container_name: psymetrica-app
        ports:
            - 8000:8000
        env_file:
            - .env
        depends_on:
            - db
        volumes:
            - .:/app
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        networks:
            - psymetrica
    db:
        image: postgres:15.3-bullseye
        container_name: psymetrica-db
        env_file:
            - .env
        ports:
            - 5432:5432
        networks:
            - psymetrica

networks:
    psymetrica:
        driver: bridge
volumes:
    static_volume:
    media_volume:
