version: "3.9"

services:
    db:
        image: postgres:15.3-bullseye
        container_name: psymetrica-db
        env_file:
            - .env
        ports:
            - 5432:5432
        networks:
            - psymetrica
    web:
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        container_name: psymetrica-app
        expose:
            - 8000
        env_file:
            - .env
        volumes:
            - .:/app
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        networks:
            - psymetrica
        depends_on:
            - db
    mailhog:
        image: mailhog/mailhog:v1.0.1
        container_name: psymetrica-mailhog
        ports:
            - 8025:8025
        networks:
            - psymetrica
    web-server:
        build:
            context: ./docker/nginx
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - 8080:80
        volumes:
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        depends_on:
            - web
        networks:
            - psymetrica
networks:
    psymetrica:
        driver: bridge
volumes:
    static_volume:
    media_volume:
