# Generated by Django 4.2.3 on 2024-01-04 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scale",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Дата удаления",
                    ),
                ),
                ("name", models.CharField(max_length=125, verbose_name="Scale name")),
                (
                    "description",
                    models.TextField(
                        max_length=255, null=True, verbose_name="Description"
                    ),
                ),
            ],
            options={
                "verbose_name": "scale",
                "verbose_name_plural": "scales",
                "ordering": ["-created_at"],
            },
        ),
    ]
