# Generated by Django 4.2.3 on 2024-03-25 12:10

import colorfield.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scale",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Дата удаления",
                    ),
                ),
                ("title", models.CharField(max_length=125, verbose_name="Название")),
                (
                    "description",
                    models.TextField(
                        max_length=255, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#ff0000",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="Цвет шкалы в графиках",
                    ),
                ),
            ],
            options={
                "verbose_name": "шкала",
                "verbose_name_plural": "шкалы",
                "ordering": ["test", "-created_at"],
            },
        ),
    ]
