# Generated by Django 4.2.3 on 2024-01-05 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tests", "0001_initial"),
        ("scales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scale",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scales",
                related_query_name="scale",
                to="tests.test",
            ),
        ),
    ]
