# Generated by Django 4.2.3 on 2024-01-16 09:35

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scales", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scale",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
