# Generated by Django 4.2.3 on 2024-01-04 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Дата удаления",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(default=1, verbose_name="Номер ответа"),
                ),
                (
                    "min_range",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Минимальный порог"
                    ),
                ),
                (
                    "max_range",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Максимальный порог"
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Текст варианта ответа",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="test_options",
                        verbose_name="Изображение варианта ответа",
                    ),
                ),
            ],
            options={
                "verbose_name": "вариант ответа",
                "verbose_name_plural": "варианты ответа",
                "ordering": ["number", "-created_at"],
            },
        ),
    ]
