# Generated by Django 4.2.3 on 2024-01-05 05:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("options", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="option",
            options={
                "ordering": ["question", "number", "-created_at"],
                "verbose_name": "вариант ответа",
                "verbose_name_plural": "варианты ответа",
            },
        ),
        migrations.AlterModelOptions(
            name="optionscore",
            options={
                "verbose_name": "балл варианта ответа",
                "verbose_name_plural": "баллы вариантов ответа",
            },
        ),
    ]
