# Generated by Django 4.2.3 on 2024-01-26 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scales", "0002_initial"),
        ("options", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optionscore",
            name="option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scores",
                to="options.option",
                verbose_name="Вариант ответа",
            ),
        ),
        migrations.AlterField(
            model_name="optionscore",
            name="scale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scales.scale",
                verbose_name="Шкала",
            ),
        ),
    ]
