# Generated by Django 4.2.3 on 2024-01-06 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("options", "0003_alter_option_options_alter_optionscore_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optionscore",
            name="option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scores",
                to="options.option",
            ),
        ),
    ]
