# Generated by Django 4.2.3 on 2024-01-27 01:15

import apps.options.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("options", "0003_alter_optionscore_option_alter_optionscore_scale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageoption",
            name="image",
            field=models.ImageField(
                upload_to=apps.options.models.filename_to_uuid,
                verbose_name="Изображение варианта ответа",
            ),
        ),
    ]
