# Generated by Django 4.2.3 on 2024-01-17 11:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        (
            "questions",
            "0004_questiongroup_question_image_question_is_required_and_more",
        ),
        ("options", "0004_alter_optionscore_option"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="option",
            unique_together={("question", "number")},
        ),
        migrations.CreateModel(
            name="TextOption",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Дата удаления",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        max_length=255, verbose_name="Текст варианта ответа"
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_option",
                        to="options.option",
                        verbose_name="Вариант ответа",
                    ),
                ),
            ],
            options={
                "verbose_name": "текстовый вариант ответа",
                "verbose_name_plural": "текстовые варианты ответа",
            },
        ),
        migrations.CreateModel(
            name="RangeOption",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Дата удаления",
                    ),
                ),
                ("min_range", models.IntegerField(verbose_name="Минимальный порог")),
                ("max_range", models.IntegerField(verbose_name="Максимальный порог")),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="range_option",
                        to="options.option",
                        verbose_name="Вариант ответа",
                    ),
                ),
            ],
            options={
                "verbose_name": "вариант ответа с картинкой",
                "verbose_name_plural": "варианты ответа с картинкой",
            },
        ),
        migrations.CreateModel(
            name="ImageOption",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Дата удаления",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="test_options",
                        verbose_name="Изображение варианта ответа",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_option",
                        to="options.option",
                        verbose_name="Вариант ответа",
                    ),
                ),
            ],
            options={
                "verbose_name": "вариант ответа с картинкой",
                "verbose_name_plural": "варианты ответа с картинкой",
            },
        ),
        migrations.RemoveField(
            model_name="option",
            name="image",
        ),
        migrations.RemoveField(
            model_name="option",
            name="max_range",
        ),
        migrations.RemoveField(
            model_name="option",
            name="min_range",
        ),
        migrations.RemoveField(
            model_name="option",
            name="text",
        ),
    ]
