# Generated by Django 4.2.3 on 2024-01-04 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("options", "0001_initial"),
        ("attempts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attemptanswers",
            name="option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                related_query_name="answer",
                to="options.option",
            ),
        ),
    ]
