# Generated by Django 4.2.3 on 2024-01-04 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tests", "0001_initial"),
        ("attempts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tests.test"
            ),
        ),
    ]
