# Generated by Django 4.2.3 on 2024-02-13 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("scales", "0001_initial"),
        ("attempts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attemptanswer",
            name="scale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scales.scale",
                verbose_name="Шкала",
            ),
        ),
    ]
