# Generated by Django 4.2.3 on 2024-01-17 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "options",
            "0005_alter_option_unique_together_textoption_rangeoption_and_more",
        ),
        ("attempts", "0005_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attemptanswer",
            unique_together={("attempt", "option")},
        ),
    ]
