# Generated by Django 4.2.3 on 2023-07-10 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scales", "0001_initial"),
        ("tests", "0001_initial"),
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="scale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                related_query_name="scale",
                to="scales.scale",
                verbose_name="Scale",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                related_query_name="test",
                to="tests.test",
                verbose_name="Test",
            ),
        ),
    ]
