# Generated by Django 4.2.3 on 2024-01-06 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionimage",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="questions.question",
                verbose_name="Вопрос",
            ),
        ),
    ]
