# Generated by Django 4.2.3 on 2023-07-18 04:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_question_scale_alter_question_test"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["number", "-created_at"],
                "verbose_name": "question",
                "verbose_name_plural": "questions",
            },
        ),
        migrations.RemoveField(
            model_name="question",
            name="scale",
        ),
    ]
