# Generated by Django 4.2.3 on 2024-01-27 01:15

import apps.questions.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.questions.models.filename_to_uuid,
                verbose_name="Изображение",
            ),
        ),
    ]
