# Generated by Django 4.2.3 on 2024-02-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0003_alter_question_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("single_option", "Вопрос с одним вариантом ответа"),
                    ("multiple_options", "Вопрос с несколькими вариантами ответа"),
                    ("text", "Вопрос с открытым ответом"),
                    ("range", "Вопрос с диапазоном"),
                    ("image", "Вопрос с выбором из картинок"),
                    ("matrix_single", "Вопрос с выбором одного ответа по строке"),
                    ("matrix_mutli", "Вопрос с выбором нескольких ответов по строке"),
                    ("intro", "Ознакомительный материал"),
                ],
                max_length=30,
                verbose_name="Тип вопроса",
            ),
        ),
    ]
