# Generated by Django 4.2.3 on 2023-07-18 05:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("questions", "0003_alter_question_options_remove_question_scale"),
        ("scales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("text", models.CharField(max_length=125, verbose_name="Answer Text")),
                (
                    "number",
                    models.IntegerField(
                        blank=True, default=1, verbose_name="Answer Number"
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        blank=True, default=1, verbose_name="Answer points"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="create timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="update timestamp"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="delete timestamp",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        related_query_name="question",
                        to="questions.question",
                        verbose_name="Question",
                    ),
                ),
                (
                    "scale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scales.scale",
                        verbose_name="Scale",
                    ),
                ),
            ],
            options={
                "verbose_name": "answer",
                "verbose_name_plural": "answers",
                "ordering": ["number", "-created_at"],
            },
        ),
    ]
