# Generated by Django 4.2.3 on 2024-01-04 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("scales", "0001_initial"),
        ("answers", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="scale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scales.scale",
                verbose_name="Scale",
            ),
        ),
    ]
