# Generated by Django 4.2.3 on 2024-01-23 05:35

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/default.jpg",
                null=True,
                upload_to=apps.users.models.filename_to_uuid,
                verbose_name="Фото профиля",
            ),
        ),
    ]
