# Generated by Django 4.2.3 on 2024-01-05 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tests", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignedTest",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Дата удаления",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_by_tests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто назначил",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_to_tests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кому назначено",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tests.test",
                        verbose_name="Тест",
                    ),
                ),
            ],
            options={
                "verbose_name": "Назначение теста",
                "verbose_name_plural": "Назначения теста",
                "ordering": ["assigned_to", "test", "-created_at"],
            },
        ),
    ]
