# Generated by Django 4.2.3 on 2024-01-23 05:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="test",
            options={
                "ordering": ["-created_at"],
                "permissions": [("can_assign_tests", "Может назначать тесты")],
                "verbose_name": "тест",
                "verbose_name_plural": "тесты",
            },
        ),
    ]
