# Generated by Django 4.2.3 on 2024-01-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0003_alter_test_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(
                db_index=True, max_length=255, unique=True, verbose_name="Название"
            ),
        ),
    ]
