# Generated by Django 4.2.3 on 2024-01-17 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0005_category_test_is_published_test_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tests",
                to="tests.category",
                verbose_name="категория",
            ),
        ),
    ]
