# Generated by Django 4.2.3 on 2024-01-21 10:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Дата удаления",
                    ),
                ),
                (
                    "text",
                    models.TextField(max_length=255, verbose_name="Текст уведомления"),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("unfinished_test", "Не завершенный тест"),
                            ("assigned_test", "Назначен тест"),
                            ("published_test", "Тест опубликован"),
                        ],
                        max_length=30,
                        verbose_name="Тема уведомления",
                    ),
                ),
            ],
            options={
                "verbose_name": "уведомление",
                "verbose_name_plural": "уведомления",
                "ordering": ["-created_at"],
            },
        ),
    ]
